<?php

namespace rombar\adminBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserQueryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserQueryRepository extends EntityRepository
{
}
